name: "ChatGPT Integration"
description: "This action integrates ChatGPT into your CI."
branding:
  icon: activity
  color: green

inputs:
  mode:
    description: "Mode"
    required: true
    default: "pr"

outputs:
  comment:
    description: "The comment from chatgpt."
runs:
  using: 'node16'
  main: 'dist/index.js'
